package app

// @title           Users CRUD API
// @version         1.0
// @description     A simple CRUD API for managing users.

// @contact.name   API Support
// @contact.email  support@example.com

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name X-API-KEY

import (
	_ "assignment2/docs" // generated by swag init
	"assignment2/internal/repository"
	"assignment2/internal/repository/_postgres"
	"assignment2/internal/usecase"
	"assignment2/pkg/modules"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	httpSwagger "github.com/swaggo/http-swagger"
)

type App struct {
	usecases *usecase.Usecases
}

func Run() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	cfg := initPostgreConfig()

	dbDialect := _postgres.NewPGXDialect(ctx, cfg)

	repos := repository.NewRepositories(dbDialect)
	logic := usecase.NewUsecases(repos)

	application := &App{usecases: logic}

	// API mux — protected by auth middleware
	// Go 1.22+ allows method and path parameters in ServeMux
	apiMux := http.NewServeMux()
	apiMux.HandleFunc("GET /health", application.HealthHandler)
	apiMux.HandleFunc("GET /users", application.getUsers)
	apiMux.HandleFunc("GET /users/{id}", application.getUserByID)
	apiMux.HandleFunc("POST /users", application.createUser)
	apiMux.HandleFunc("PUT /users/{id}", application.updateUser)
	apiMux.HandleFunc("DELETE /users/{id}", application.deleteUser)

	// Top-level mux — swagger is public, everything else goes through auth
	rootMux := http.NewServeMux()
	rootMux.Handle("/swagger/", httpSwagger.WrapHandler)
	rootMux.Handle("/", application.AuthMiddleware(apiMux))

	// Single top-level logging middleware for everything
	finalHandler := application.LoggingMiddleware(rootMux)

	srv := &http.Server{
		Addr:    ":8080",
		Handler: finalHandler,
	}

	go func() {
		fmt.Println("🚀 Server starting on :8080...")
		fmt.Println("📖 Swagger UI: http://localhost:8080/swagger/index.html")
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %s", err)
		}
	}()

	<-ctx.Done()
	log.Println("Shutting down server...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Fatalf("Server forced to shutdown: %v", err)
	}

	log.Println("Server exiting")
}

// HealthHandler godoc
// @Summary      Health check
// @Description  Returns service health status
// @Tags         health
// @Produce      json
// @Success      200  {object}  map[string]string
// @Router       /health [get]
func (a *App) HealthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.Write([]byte(`{"status": "ok"}`))
}

// getUsers godoc
// @Summary      List users
// @Description  Get paginated list of active (non-deleted) users
// @Tags         users
// @Produce      json
// @Param        limit   query     int  false  "Max number of results (default 10)"
// @Param        offset  query     int  false  "Number of results to skip"
// @Success      200     {array}   modules.User
// @Failure      500     {object}  map[string]string
// @Security     ApiKeyAuth
// @Router       /users [get]
func (a *App) getUsers(w http.ResponseWriter, r *http.Request) {
	limit, _ := strconv.Atoi(r.URL.Query().Get("limit"))
	offset, _ := strconv.Atoi(r.URL.Query().Get("offset"))
	if limit == 0 {
		limit = 10
	}

	users, err := a.usecases.GetAllUsers(limit, offset)
	if err != nil {
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(users)
}

// getUserByID godoc
// @Summary      Get user by ID
// @Description  Get a single user by its unique ID
// @Tags         users
// @Produce      json
// @Param        id  path      int  true  "User ID"
// @Success      200     {object}  modules.User
// @Failure      400     {object}  map[string]string
// @Failure      404     {object}  map[string]string
// @Security     ApiKeyAuth
// @Router       /users/{id} [get]
func (a *App) getUserByID(w http.ResponseWriter, r *http.Request) {
	idStr := r.PathValue("id")
	id, err := strconv.Atoi(idStr)
	if err != nil || id <= 0 {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "valid id path param is required"})
		return
	}

	user, err := a.usecases.GetUserByID(id)
	if err != nil {
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(user)
}

// createUser godoc
// @Summary      Create a user
// @Description  Creates a new user record
// @Tags         users
// @Accept       json
// @Produce      json
// @Param        user  body      modules.User  true  "User to create"
// @Success      201   {object}  map[string]int
// @Failure      400   {object}  map[string]string
// @Security     ApiKeyAuth
// @Router       /users [post]
func (a *App) createUser(w http.ResponseWriter, r *http.Request) {
	var u modules.User
	if err := json.NewDecoder(r.Body).Decode(&u); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid request body"})
		return
	}
	newID, err := a.usecases.CreateUser(u)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(map[string]int{"id": newID})
}

// updateUser godoc
// @Summary      Update a user
// @Description  Updates an existing user by ID
// @Tags         users
// @Accept       json
// @Produce      json
// @Param        id    path      int           true  "User ID"
// @Param        user  body      modules.User  true  "Updated user data"
// @Success      200   {object}  map[string]string
// @Failure      400   {object}  map[string]string
// @Failure      404   {object}  map[string]string
// @Security     ApiKeyAuth
// @Router       /users/{id} [put]
func (a *App) updateUser(w http.ResponseWriter, r *http.Request) {
	idStr := r.PathValue("id")
	id, err := strconv.Atoi(idStr)
	if err != nil || id <= 0 {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "valid id path param is required"})
		return
	}
	var u modules.User
	if err := json.NewDecoder(r.Body).Decode(&u); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "invalid request body"})
		return
	}
	if err := a.usecases.UpdateUser(id, u); err != nil {
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]string{"status": "updated"})
}

// deleteUser godoc
// @Summary      Delete a user
// @Description  Soft-deletes a user by setting deleted_at timestamp
// @Tags         users
// @Produce      json
// @Param        id  path      int  true  "User ID"
// @Success      204
// @Failure      400  {object}  map[string]string
// @Failure      404  {object}  map[string]string
// @Security     ApiKeyAuth
// @Router       /users/{id} [delete]
func (a *App) deleteUser(w http.ResponseWriter, r *http.Request) {
	idStr := r.PathValue("id")
	id, err := strconv.Atoi(idStr)
	if err != nil || id <= 0 {
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "valid id path param is required"})
		return
	}
	if err := a.usecases.DeleteUser(id); err != nil {
		w.WriteHeader(http.StatusNotFound)
		json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func initPostgreConfig() *modules.PostgreConfig {
	return &modules.PostgreConfig{
		Host:        getEnv("DB_HOST", "localhost"),
		Port:        getEnv("DB_PORT", "5432"),
		Username:    getEnv("DB_USER", "postgres"),
		Password:    getEnv("DB_PASSWORD", "root"),
		DBName:      getEnv("DB_NAME", "mydb"),
		SSLMode:     getEnv("DB_SSLMODE", "disable"),
		ExecTimeout: 5 * time.Second,
	}
}

func getEnv(key, fallback string) string {
	if value, ok := os.LookupEnv(key); ok {
		return value
	}
	return fallback
}
